version: '2'
services:
    jhipstertestoctober-app:
        image: jhipstertestoctober
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstertestoctober-mysql:3306/jhipstertestoctober?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipstertestoctober-mysql:
        extends:
            file: mysql.yml
            service: jhipstertestoctober-mysql
